name: news-scraper-records

up:
  - ruby: 2.3.1
  - bundler
  - homebrew:
    - postgresql
  - custom:
      name: Start Postgres
      met?: test -f "/usr/local/var/postgres/postmaster.pid"
      meet: |
        pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start &
        sleep 1
  - custom:
      name: ejson setup
      met?: test -d /opt/ejson/keys
      meet: mkdir -p /opt/ejson/keys
  - custom:
      name: ejson keys
      met?: test -f /opt/ejson/keys/92aca905807945b265474a0c05565bce907fcff444e8bb120bf5ae40ce87fa69
      meet: echo "You need to set the private key in /opt/ejson/keys/92aca905807945b265474a0c05565bce907fcff444e8bb120bf5ae40ce87fa69"
  - database:
      vendor: postgres
      bootstrap: bundle exec rake db:create
      migrate: bundle exec rake db:migrate
      host: ""
      user: ""
      password: ""
      database: news_scraper_records

commands:
  encrypt: bin/encrypt
  prod_sync: ENV=production bundle exec rake db:migrate
  train: bundle exec bin/train
